[project]
src = "src"

# parameter for every network i.e. if address is not specified, it will be deployed
[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"
save_to_db = false

[networks.contracts.coffee]
deployer_script = "script/deploy.py"

[networks.sepolia]
url="$SEPOLIA_RPC_URL"
save_to_db = false
default_account_name = "default"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

#[networks.pyevm.contracts.price_feed]
#deployer_script = "script/deploy_mocks.py"

[networks.anvil]
url="http://127.0.0.1:8545"
save_to_db = true
default_account_name = "anvil1"

# parameter for every network i.e. if on sepolia it will use the address below and if not sepolia it will deploy the contract
[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
deployer_script = "script/deploy_mocks.py"

# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
